### ISSUE TITLE
sentiment over time

### ISSUE THREAD

**Issue by Err0neus** [Err0neus/Project_Santos#21]
Add charts to Visualisations - Sentiment Analysis
• create new tab (name "Sentiment Over Time")
• 1 chart not split by charted/uncharted... just tracks by sentiment group over time
• + 2 charts splitting the above to Charted and Uncharted 
• if possible, manipulate Y axis lables not to show negative sign (i.e. 10-5-0-5-10)
• adjust bar widht to 0.9 [i.e. in ax.bar(x, y_ntr2, width = **0.9**, color = '#b2b2b2')]

source notebook: Project_Santos/_support files/DC_dev_file.ipynb

**Comment by Chitra0790** [comment]
Have add to UI.. Need to review

**Comment by Chitra0790** [comment]
Done

**Comment by Err0neus** [comment]
**FEEDBACK:**
**-> cosmetics:**
• x labels on UNCHARTED TRACKS (bottom right) are not aligned with the other 2 charts
• size chart - let's make it horizontally a little wider, but vertically shorter... something like a "widescreen" ratio? 
• apply the new color scheme
**-> ERROR**
• chart fails when trying with these configurations:
-- Artist = Nirvana | Albums = Bleach, Nevermind, In Utero
-- Artist = Fontaines D.C. | Albums = Dogrel, A Hero's Death

**Comment by Err0neus** [comment]
errors fixed
colors set - palette to be fixed (issue #24)
data representation (e.g. y axis labels vs bar labels vs hovering)  opened as anothe issue (#25)
