### ISSUE TITLE
wrong tracklist when duplicate album name

### ISSUE THREAD

**Issue by Err0neus** [Err0neus/Project_Santos#38]
see David Bowie albums
1967 - album name = "David Bowie"
1969 - album name = "David Bowie"
result -> same tracklist !!

**Comment by Err0neus** [comment]
let's try to have 3 columns for tracklist
- TRACK_TITLE_DISCOGS > always taken with the discogs discography
- TRACK_TITLE_GENIUS -> searched as usual, blank if not found BUT matched to discogs with Levinshtein method... anything unmatched creates additional rows with discog name null
****this search must also consider duplicates. if albums from different years have same name, second search should include first** DISCOG track name in the url (David Bowie 1967/1969)**

- TRACK_TITLE -> genius if not null, discogs if null

**Comment by Err0neus** [comment]
mockup attached
[discog_store_new.xlsx](https://github.com/Err0neus/Project_Santos/files/6170384/discog_store_new.xlsx)
![image](https://user-images.githubusercontent.com/43116506/111766213-2e1fa180-889d-11eb-83bf-bad713b7f1ad.png)

**Comment by Chitra0790** [comment]
Created duplicate flag to solve the problems for David Bowie. Need to test more

**Comment by Err0neus** [comment]
Tracklist seem good, but Albums are not uniquely identified (see Red House Painters 1993)
Solution - Year/Album column to uniquely identify duplications
in the process change ARTIST_ID to DISCOGS_ALBUM_ID (must have) + DISCOGS_ARTIST_ID (nice to have)

**Comment by Err0neus** [comment]
@Chitra0790 
Assigning back to you. I will create a new issue for the displaying of the same year/album (Red House Painters)
This issue will be kept for the original problem, that still persists:

see David Bowie albums
1967 - album name = "David Bowie"
1969 - album name = "David Bowie"
result -> same tracklist !!

**Comment by Err0neus** [comment]
done!!!
