### ISSUE TITLE
DISCOG_AVG_RATING not numeric

### ISSUE THREAD

**Issue by Err0neus** [Err0neus/Project_Santos#7]
DISCOG_AVG_RATING returns non numeric value "--" in some cases.
Breaks the charts.
Can we ensure all DISCOG columns are numeric?

Example: NIRVANA - Incesticide 
![image](https://user-images.githubusercontent.com/43116506/88694933-139e7b00-d0b6-11ea-82eb-99a8ac58d396.png)

**Comment by Chitra0790** [comment]
I have now converted all the discog columns to Integer.

**Comment by Chitra0790** [comment]
Discog Columns converted to integer
